export const cardArray = [
  {
    id: 0,
    title: 'Первый товар',
    price: '170 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: '1.Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 1,
    title: 'Второй товар',
    price: '171 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: '2.Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 2,
    title: 'Третий товар',
    price: '172 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: '3.Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 3,
    title: 'Четвертый товар',
    price: '173 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: '4.Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 4,
    title: 'Пятый товар',
    price: '174 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: '5.Продаю не спеша самокат в хорошем состоянии.',
  },
  {
    id: 5,
    title: 'Шестой товар',
    price: '175 ₽',
    adress: 'Казань, р-н Вахитовский',
    date: '10 июля 11:39',
    img: '/image/card-img.png',
    description: '6.Продаю не спеша самокат в хорошем состоянии.',
  },
]
